# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 10:44
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pr\xe9nom')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('picture', models.ImageField(null=True, upload_to='actors', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('director', models.CharField(blank=True, max_length=100, null=True, verbose_name='R\xe9alisateur')),
                ('lenght', models.TimeField(blank=True, max_length=100, null=True, verbose_name='Dur\xe9e')),
                ('picture', models.ImageField(null=True, upload_to='covers', verbose_name='Photo')),
                ('release_date', models.DateTimeField()),
                ('rented', models.BooleanField()),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True, verbose_name='Slug')),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre')),
                ('trailer_url', models.URLField()),
                ('actors', models.ManyToManyField(blank=True, null=True, to='rentmanager.Actor', verbose_name='Acteurs')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('action', 'Action'), ('romance', 'Romance'), ('science-fiction', 'Science-Fiction'), ('comedie-musicale', 'Com\xe9die Musicale'), ('historique', 'Historique'), ('arts-martiaux', 'Arts-Martiaux')], default='action', max_length=100, verbose_name='Genre')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='label', unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='MovieRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentmanager.Customer')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentmanager.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentmanager.MovieGenre'),
        ),
    ]
