# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0002_auto_20181105_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='rentmanager.Actor', verbose_name='Acteurs'),
        ),
    ]
