# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0003_auto_20181105_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Genre'),
        ),
    ]
