# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0005_auto_20181105_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='rentmanager.Actor', verbose_name='Acteurs'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='R\xe9alisateur'),
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
