# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0008_auto_20181105_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='actors', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='director',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='directors', verbose_name='Photo'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='rentmanager.Actor'),
        ),
    ]
