# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0010_auto_20181105_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='rentmanager.Actor'),
        ),
    ]
