# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0015_auto_20181106_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
    ]
