# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0016_remove_actor_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(to='rentmanager.Movie'),
        ),
    ]
