# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0020_auto_20181106_2124'),
        ('rentmanager', '0021_auto_20181106_2034'),
    ]

    operations = [
    ]
