# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 10:13
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0025_auto_20181111_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movies', to='rentmanager.Actor', verbose_name='actors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentmanager.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentmanager.Director', verbose_name='director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentmanager.MovieGenre', verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='lenght',
            field=models.TimeField(blank=True, max_length=100, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(verbose_name='release date'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rented',
            field=models.BooleanField(default=False, verbose_name='rented'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, null=True, verbose_name='synopsis'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Trailer url'),
        ),
    ]
