# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 13:18
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0026_auto_20181112_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='actors', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='director',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='director',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='director',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='directors', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='lenght',
            field=models.TimeField(blank=True, max_length=100, null=True, verbose_name='lenght'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='trailer url'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='label', unique=True, verbose_name='slug'),
        ),
    ]
