# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0028_auto_20181112_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'movie'},
        ),
    ]
