# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0029_auto_20181112_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
            ],
            options={
                'managed': True,
                'db_table': 'rentmanager_country_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'country Translation',
            },
        ),
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'actor'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'director'},
        ),
        migrations.AlterModelOptions(
            name='moviegenre',
            options={'verbose_name': 'genre'},
        ),
        migrations.AlterModelOptions(
            name='movierent',
            options={'verbose_name': 'rent'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.AddField(
            model_name='countrytranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='rentmanager.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='countrytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
