# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 15:06
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0030_auto_20181112_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenreTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='genre')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='label', unique=True, verbose_name='slug')),
            ],
            options={
                'managed': True,
                'db_table': 'rentmanager_moviegenre_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'genre Translation',
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='label',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='slug',
        ),
        migrations.AddField(
            model_name='moviegenretranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='rentmanager.MovieGenre'),
        ),
        migrations.AlterUniqueTogether(
            name='moviegenretranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
